-- 코드를 입력하세요
SELECT inn.ANIMAL_ID,inn.NAME
FROM ANIMAL_INS AS inn
INNER JOIN ANIMAL_OUTS AS outt
ON inn.ANIMAL_ID = outt.ANIMAL_ID
WHERE inn.DATETIME > outt.DATETIME
# GROUP BY outt.ANIMAL_ID
ORDER BY inn.DATETIME ASC;

